name: FastBenchmark
author: Meigo™ Corporation
version: 1.3
description: A comprehensive Minecraft server benchmarking plugin for performance monitoring and analysis.
main: meigo.north.MeigoPlugin
api-version: 1.13
softdepend: [PlaceholderAPI]
commands:
  fastbenchmark:
    description: Main FastBenchmark command
    aliases: [fb]
    usage: /<command> help
  cpubar:
    description: Toggle CPU monitoring boss bar
    usage: /<command> <player>
  rambar:
    description: Toggle RAM monitoring boss bar
    usage: /<command> <player>
  realrambar:
    description: Toggle real RAM monitoring boss bar (fallback)
    usage: /<command> <player>
  noderambar:
    description: Toggle system RAM monitoring boss bar
    usage: /<command> <player>
  addram:
    description: Allocate RAM for testing
    usage: /<command> <megabytes>
  ramfree:
    description: Free allocated RAM
    usage: /<command>
  speedtest:
    description: Run network speed test
    usage: /<command>
permissions:
  fastbenchmark.admin:
    description: Access to all FastBenchmark commands
    default: op
  fastbenchmark.speedtest:
    description: Access to speed test command
    default: op